<a href="https://colab.research.google.com/github/LeeSeongJinn/Doosan_Rokey_bootcamp/blob/main/1_Basic_AI/3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# numpy 부동소수점 자리수 표시
np.set_printoptions(suppress=True, precision=3)

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
n1 = np.array([1,2,3,4,5])
print(n1)
# 요소 수 확인
print(n1.shape) # 1차원 (5, )

[1 2 3 4 5]
(5,)


In [ ]:
len(n1)

5

In [ ]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
n2 = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
print(n2)
print(n2.shape)
# 2차원, (4, 3)
# >> 4행 3열, 4개의 배열, 각 배열마다 3개의 원소(속성)가 있다. 원소 개수 12개

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
print(len(n2))

4


zeros(), ones() 함수이용

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
n3 = np.zeros(5)
n3.shape # (5,) 1차원

(5,)

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
n4 = np.ones((2,3))
print(n4)
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [ ]:
# 모든 요소 정규분포를 따르는변수와 3개의 행렬
np.random.randn(2,3,4)
# random: 무작위, 임의로(임의적) >> 일반화
# randn (n: normalize 정규화) >> 정규분포 (평균 0, 표준편차 1)
# 표준화 (x - x_bar) / sigma
# >> x :원래 값, x_bar: 평균, sigma 편차(평균에서 떨어진 값)
# 정규화 (x-x_min) / (x_max - x_min) >> [0,1]
# >> x: 원래 값, x_min : 해당 속성(열) 최소값, x_max : 해당 속성(열) 최대값
# n으로 나눈다 n = len(x)

array([[[-0.479, -0.822, -0.464,  0.286],
        [ 0.826, -0.498, -0.025,  0.628],
        [-0.836, -0.103,  0.717,  2.145]],

       [[ 0.546,  0.861, -0.538,  1.06 ],
        [-0.635, -0.39 , -0.675,  0.55 ],
        [-0.408,  0.087,  0.8  ,  0.244]]])

In [ ]:
np.random.randn(2,3,4).shape
# (2,3,4) : 3개의 배열, 각 배열마다 4개의 원소(속성) 가지고 있는 행렬이 2개

(2, 3, 4)

In [ ]:
n5 = np.random.randn(2,3,4)
print(n5.shape)

(2, 3, 4)


그래프 출력용 수치 배열 생성

In [ ]:
np.linspace(-1, 1, 11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [ ]:
n6 = np.linspace(-1, 1, 11)
print(n6.shape) # (11,) 1차원

(11,)


In [ ]:
n6.ndim
# ndim : number of dimension 차원 수

1

In [ ]:
np.arange(-1, 1.2, 0.2)

array([-1. , -0.8, -0.6, -0.4, -0.2, -0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

조작(manupulation)

In [ ]:
# 특정 행, 열 추출
print(n2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(n2.shape)

(4, 3)


In [ ]:
n2[:, 0]

array([ 1,  4,  7, 10])

In [ ]:
n2[:, 0].shape # 1차원 (4, )

(4,)

In [ ]:
np.array([False, True, False, True])

array([False,  True, False,  True])

In [ ]:
n7 = np.array([False, True, False, True])

print(n2)
print()
print(n2[n7]) # 마스크 추출

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 4  5  6]
 [10 11 12]]


In [ ]:
n8 = n2[n7]
n8.shape

(2, 3)

reshape(중요)

In [ ]:
# 초기 변수 1개 배열
# list(range(24))
np.array(range(24))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
n9 = np.array(range(24))
n9.shape # (24,) 1차원 >> 원소 24

(24,)

In [ ]:
n9.reshape(3, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
n9.reshape(3, 8).shape # 2차원

(3, 8)

In [ ]:
n9.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
n9.reshape(2,2,-1) # 3차원

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
n9.reshape(2, 2,2,-1)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [ ]:
# n9.reshape(3,9)
# ValueError: cannot reshape array of size 24 into shape (3,9)

In [ ]:
# -1 지정, 자동 계산
n9.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
n9.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

축 교체하기

In [ ]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
n2.shape

(4, 3)

In [ ]:
# 전치행렬 (위치를 바꾸는 행렬, 행과 열 바꾸는 것)
# T : transpose
n2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
n2.T.shape

(3, 4)

In [ ]:
n9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
n9.reshape(2, -1 , 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
n10 = n9.reshape(2, -1 , 4)
n10.shape

(2, 3, 4)

In [ ]:
np.transpose(n10)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
np.transpose(n10).shape

(4, 3, 2)

In [ ]:
np.transpose(n10, (1,2,0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [ ]:
np.transpose(n10, (1,2,0)).shape

(3, 4, 2)

In [ ]:
np.transpose(n10, (2,1,0))

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
np.transpose(n10, (2,1,0)).shape

(4, 3, 2)

In [ ]:
one_d  = np.array([1,2,3,4,5])

print(one_d)        # 1차원
print(one_d.shape)  # (5, )

[1 2 3 4 5]
(5,)


In [ ]:
print(one_d.T) # 1차원
print(one_d.T.shape)

[1 2 3 4 5]
(5,)


In [ ]:
np.reshape(one_d, (5, 1))
two_d = np.reshape(one_d, (5, 1))
print(two_d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
two_d.shape # 2차원

(5, 1)

In [ ]:
two_d.T

array([[1, 2, 3, 4, 5]])

In [ ]:
two_d.T.shape

(1, 5)

행렬 연결하기

In [ ]:
np.array(range(1,7))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array(range(1,7)).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2행 3열 행렬
n13 = np.array(range(1,7)).reshape(2,3)
n14 = np.array(range(7,13)).reshape(2,3)

In [ ]:
print(n13)
print()
print(n14)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [ ]:
# 행렬과 행렬 연결(n13, n14)
# vstack() : vertically stack 수직으로 쌓아줘
np.vstack([n13, n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.vstack([n13, n14]).shape

(4, 3)

In [ ]:
# hstack (horizontally stack) 수평으로 쌓아줘
np.hstack([n13, n14])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.hstack([n13, n14]).shape

(2, 6)

In [ ]:
np.concatenate([n13, n14])  # vstack()과 같다

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([n13, n14], axis=0) # axis=0 (default 기본설정)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([n13, n14], axis=1) # hstack()과 같음

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.concat([n13, n14], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

연산

In [ ]:
# 넘파이 변수끼리 연산
# 원본
print(n13)
print()
print(n14)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [ ]:
n13 + n14
# 넘파이 배열이라 연산 가능(원소끼리 element-wise)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
n15 = n13 + n14
n15

array([[ 8, 10, 12],
       [14, 16, 18]])

브로드캐스팅

In [ ]:
print(n1) # 벡터

[1 2 3 4 5]


In [ ]:
# 모든 요소에서 같은 값을뺀다
n1 - 3 # 3 : 0차원(스칼라, scala)

array([-2, -1,  0,  1,  2])

유니버셜 함수

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 2*np.pi, 5)

array([0.   , 1.571, 3.142, 4.712, 6.283])

In [ ]:
x = np.linspace(0, 2*np.pi, 5)
y = np.sin(x)

print(y)

[ 0.  1.  0. -1. -0.]


집계함수

In [ ]:
n1

array([1, 2, 3, 4, 5])

In [ ]:
np.sum(n1) # 15 (scala)

np.int64(15)

In [ ]:
np.mean(n1)

np.float64(3.0)

In [ ]:
np.max(n1)

np.int64(5)

In [ ]:
np.min(n1)

np.int64(1)

응용예시

In [ ]:
# 두 변수를 비교해서 일치하는 개수로 정확도 계산

# 2개의 넘파이 배열 준비

# 정답
yt = np.array([1,1,0,1,0,1,1,0,1,0])

# 예측
yp = np.array([1,1,0,1,0,1,0,1,1,1])

In [ ]:
# 정답(yt)와 예측(yp) 잘 맞았나? (비교)

(yt == yp)

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False])

In [ ]:
matched = (yt == yp)
matched.sum()

np.int64(7)

In [ ]:
# 맞은 개수(정답 수 세는 방법)
correct = matched.sum()

# 전체 수
total = len(matched)

# 정확도 계산
accuracy = correct / total
print(accuracy)

0.7


In [ ]:
print(f'정답수: {correct}, 전체 개수: {total}, 정확도:{accuracy*100}%')

정답수: 7, 전체 개수: 10, 정확도:70.0%


정규화 : 벡터 값은 1차함수로 변환 [0,1] 범위로 제한

In [ ]:
# 모든 값을 [0,1] 범위에 포함되도록
n1

array([1, 2, 3, 4, 5])

In [ ]:
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

5 1


In [ ]:
# (x-x_min / x_max - x_min)
# 변환
(n1 - n1_min) / (n1_max - n1_min)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])